name: Build Frontend

on:
  push:
    branches: ["**"]
    tags: ["v*"]

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compute Tags
        id: meta
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            echo "tags=ghcr.io/${GITHUB_ACTOR}/ymm-frontend:latest,ghcr.io/${GITHUB_ACTOR}/ymm-frontend:${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            short_sha="${GITHUB_SHA::7}"
            echo "tags=ghcr.io/${GITHUB_ACTOR}/ymm-frontend:latest,ghcr.io/${GITHUB_ACTOR}/ymm-frontend:${short_sha}" >> $GITHUB_OUTPUT
          fi
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
